language: java
install: skip
os: linux
dist: trusty
jdk: openjdk8
script:
- "./gradlew desktop:dist"
deploy:
  provider: releases
  api_key:
    secure: qxy4oQr1IgeXP9Qect32EJb2+bTrOov9Q7ZW3zwSZsEYIOsHtMO0Eyh3AM9ATfSnWi3uJBvyajpi2xEEiCyXWiJxC+ngkDvfDuHC+pvJhlCz5a5SGbyU7FxpaBAMxw6eYEchbpZg0/lGc0lOnbDwsUuXae1MVjgfa6PDPODQeq7VI4eV3/57QoT6e01U4VWMWgwQIlzi2CYVcAcqTxeLqVI9ObqGEbJOi7G3hGW0hXsDyLR449KJwP7Vkv5tX80YaZnZsThhyYGcGHO0+26JLLbvnUgebwPoMrtzIfC33cFpMu+1Xl3QSsV9lGo+YbvT9kgkQUik4HrjP8e2gpoE5nNRHoWtcsjz/wpbS1YXszsj6L/9N/R6Kxr23KxnHAkPAHHnktpmdE8xOBkHhyQNrjcFJcjoqlRhNz043hzjo9Ic4asuluar6sR1mcc+McTpf87Nhtxqyj9GFBX8JseFpmkR90SRyTd08nSKOa1tWqrx7XLgRSUOV+Z/PIuH9yxrvpDppnDLOSyJvRudPguWfZM9SrcrfdxSsbSsbbDl2x0yzF2xhy7DWDdCL7b2p3+0yIFW24rjxpjehfz/eFG0H+lUHRNeyhBtASBg2DcnBUjFdstLPapudPSwgeYOud9OIqVOvub4d9AjFrOOMtHcYcAJ5id/KZnQxL3TmVMVSWo=
  file: desktop/build/libs/Mindustry.jar
  on:
    repo: blahblahbloopster/mindustry-client-v6
    branch: custom-client
  skip_cleanup: 'true'
