language: java
install: skip
os: linux
dist: trusty
jdk: openjdk8
script:
- "./gradlew desktop:dist"
deploy:
  provider: releases
  api_key:
    secure: kSx0hfx9AiRtlFMku93Neb2u9WMozIjoodM5xjQRTWn2bAIxrg6rMh10bXIG3NwLTYOs6dfcIAaqI7IPGjlQ29bmuICsbUb1gAwIq7WG5eI95d9JmtilZ/KXuqhUSsx7iiWl6AmEJ+63RxvJ4N26XltAawVTNldcKwi3PbrVkIlRPq1hHidoaAISuKr7hTpcFAj8zksV3Qe7g+6EvHDyuzQSLrBENaEvPOQCv3JO0/8xSGGY8Ds1x+uUXBVP5aFeWLRyzS1U6N3y0TqamTgZxxIRZkhSKn7yCYpOLbeYb/lT7p5gcuX5cYDjDDQSE/HFSKiiaa2xvkIs3dnhwMGJFo+ns1DdGVbV3dS/cgEPRnlRUL0CClDXGXupLIGgpr/o6yFEFtFwo3LgXht8+wqzf32YLMqnGd7ytkybDjVgLhji9ijH0VOAPnrDFqNGSXrMfUAnyQB9FcSgufyYT9FMX52L0/zos/Bk0W6fMOPnEUSlB55+2gSAJxvH6cBkV9M9fWqFefN0eN11nDfTL7E2KPUkiJWHUwLpjLarium6Yyra/EGOuLdlV7Gna4aq7cBwfqgRXQn6yGneRH2GtiZ8GBhsZTlic2noHpwrLfJmAC/xJqQW4ENn7aYIH3ZdP+KB7UwUFwDHtTVj+3w8Sat7pmAKqHm7G2OIbmB4hT4vWaw=
  file: desktop/build/libs/Mindustry.jar
  on:
    repo: blahblahbloopster/mindustry-client-v6
    branch: custom-client
  skip_cleanup: 'true'
