blank_issues_enabled: true
contact_links:
  - name: Base Client's Discord
    url:  https://discord.gg/yp9ZW7j
    about: It is preferred that you ask questions on discord as we are typically more active there and it is easier to chat without waiting 3 hours for a reply.
