name: PR Tests

on: pull_request


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Compile test JAR
        run: ./gradlew desktop:dist

      - name: Upload desktop JAR for testing
        uses: actions/upload-artifact@v2
        with:
          name: Desktop JAR (zipped)
          path: desktop/build/libs/Mindustry.jar

      - name: Run Tests
        if: ${{ always() }}
        run: ./gradlew test
