name: Release Update

on: 
  push:
    branches: custom-client
  workflow_dispatch:
    branches: custom-client
    

jobs:
  buildAndReleaseJava14:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Workflows
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
      
    - name: Build desktop with gradle
      run: |
        ./gradlew desktop:dist -PclientBuild=${{ github.run_number }} -PupdateUrl=https://api.github.com/repos/${{ github.repository }}/releases/latest
        ./gradlew desktop:dist -PclientBuild=${{ github.run_number }} -PupdateUrl=https://api.github.com/repos/${{ github.repository }}/releases/latest -PversionModifier=steam

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Foo's Client Build ${{ github.run_number }}
          Steam installation instructions [here](https://github.com/${{ github.repository }}#steam)
        draft: false
        prerelease: false

    - name: Upload Desktop (Non-Steam) Release
      id: upload-desktop-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./desktop/build/libs/Mindustry.jar
        asset_name: desktop-release.jar
        asset_content_type: application/zip

    - name: Upload Steam Release
      id: upload-steam-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./desktop/build/libs/desktop.jar
        asset_name: steam.jar
        asset_content_type: application/zip
