name: Java Tests # Tests and pushes to unstable

on:
  push:
    branches: "**" # Runs on all branches but never on tags
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle Caching
        uses: gradle/gradle-build-action@v2

      - name: Set Env
        run: echo "SLUG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Timestamp
        id: time
        uses: 1466587594/get-current-time@v2
        with:
          format: ${[env.SLUG]}, MMM. D, YYYY [Unstable] # Pulls the tag name and current date to produce clientVersion > v1.0.0, Jan. 1, 1970

      - name: Run Tests
        run: |
          export PATH=./tools:$PATH
          ./gradlew tools:pack test desktop:dist -PupdateUrl=mindustry-antigrief/mindustry-client -PclientVersion="${{ steps.time.outputs.formattedTime }}" --parallel

      - name: Get Latest Release
        id: get_release
        uses: gregziegan/fetch-latest-release@v2.0.0

      - name: Delete Old Jar
        uses: flcdrg/remove-release-asset-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release_id: ${{ steps.get_release.outputs.id }}
          asset_name: erekir-client.jar

      - name: Upload New Jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: desktop/build/libs/Mindustry.jar
          asset_name: erekir-client.jar
          asset_content_type: application/zip

      - name: Update Release Name
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAG_NAME: "v8.0.0"
        with:
          release_name: ${{ steps.time.outputs.formattedTime }}