name: Java Tests # Tests and pushes to unstable

on: [push, workflow_dispatch]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with: 
          persist-credentials: false

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Run Tests
        run: ./gradlew test desktop:dist -PclientBuild=${{ github.run_number }} -PupdateUrl=${{ github.repository }}-builds

      - name: Create Release
        if: ${{ github.repository == 'mindustry-antigrief/mindustry-client-v6' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          body: |
            Foo's Client Unstable ${{ github.run_number }}
            Steam installation instructions [here](../../#steam)
            **Latest Commit Message:**
            *${{ github.event.head_commit.message }}*
          commitish: main
          tag_name: ${{ github.run_number }}
          release_name: Unstable ${{ github.run_number }}
          repo: mindustry-client-v6-builds
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: ${{ github.repository == 'mindustry-antigrief/mindustry-client-v6' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: desktop/build/libs/Mindustry.jar
          asset_name: desktop.jar
          asset_content_type: application/zip

      - name: Upload Test Results To Pages
        if: ${{ !cancelled() && github.event_name == 'push' && github.repository == 'mindustry-antigrief/mindustry-client-v6' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          REPOSITORY_NAME: ${{ github.repository }}-builds
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: tests/build/reports/tests/test
          CLEAN: true # Automatically remove deleted files from the deploy branch
