name: Java Tests # Tests and pushes to unstable

on:
  push:
    branches: "**" # Runs on all branches but never on tags
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle Caching
        uses: gradle/gradle-build-action@v2

      - name: Set Env
        run: echo "SLUG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Timestamp
        id: time
        uses: 1466587594/get-current-time@v2
        with:
          format: "[${{env.SLUG}}], MMM. D, YYYY [Unstable]" # Pulls the tag name and current date to produce clientVersion > v1.0.0, Jan. 1, 1970

      - name: Run Tests
        run: |
          ./gradlew tests:cleanTest tools:pack tests:test desktop:dist -PupdateUrl=stormybytes/mindustry-client-builds -PclientVersion="${{ steps.time.outputs.formattedTime }}" --parallel

      - name: Create Release
        if: ${{ github.repository == 'stormybytes/mindustry-client' && github.ref == 'refs/heads/flarogus' }}
        id: create_release_v7
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          body: |
            Foo's Client Unstable ${{ github.run_number }} [(${{ env.SLUG }})](https://github.com/stormybytes/mindustry-client/commit/${{ github.sha }})
            Steam installation instructions [here](../../../stormybytes/tree/v7#steam)
            **Commit Message:**
            *${{ github.event.head_commit.message }}*
          commitish: main
          tag_name: ${{ github.run_number }}
          release_name: ${{ steps.time.outputs.formattedTime }}
          repo: mindustry-client-builds
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: ${{ github.repository == 'stormybytes/mindustry-client' && github.ref == 'refs/heads/flarogus' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_v7.outputs.upload_url }}
          asset_path: desktop/build/libs/Mindustry.jar
          asset_name: desktop.jar
          asset_content_type: application/zip

      - name: Upload Artifact (No release was made)
        if: ${{ !(github.repository == 'stormybytes/mindustry-client' && (github.ref == 'refs/heads/v6' || github.ref == 'refs/heads/flarogus' || github.event_name == 'workflow_dispatch')) }}
        uses: actions/upload-artifact@v2
        with:
          name: Desktop JAR (zipped)
          path: desktop/build/libs/Mindustry.jar

      - name: Upload Test Results To Pages
        if: ${{ !cancelled() && github.repository == 'stormybytes/mindustry-client' && (github.ref == 'refs/heads/flarogus' || github.event_name == 'workflow_dispatch') }}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          repository-name: ${{ github.repository }}-builds
          branch: gh-pages # The branch the action should deploy to.
          folder: tests/build/reports/tests/test
          silent: true
          single-commit: true

      # Temporary
#      - name: Get Latest Release
#        id: get_release
#        uses: gregziegan/fetch-latest-release@v2.0.0
#
#      - name: Delete Old Jar
#        uses: flcdrg/remove-release-asset-action@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        with:
#          release_id: ${{ steps.get_release.outputs.id }}
#          asset_name: desktop.jar
#
#      - name: Upload New Jar
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        with:
#          upload_url: ${{ steps.get_release.outputs.upload_url }}
#          asset_path: desktop/build/libs/Mindustry.jar
#          asset_name: desktop.jar
#          asset_content_type: application/zip
#
#      - name: Update Release Name
#        uses: tubone24/update_release@v1.3.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#          TAG_NAME: "v8.0.0"
#        with:
#          release_name: ${{ steps.time.outputs.formattedTime }}

