name: Java Tests # Tests and pushes to unstable

on: [push, workflow_dispatch]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Run Tests
        run: |
          ./gradlew test desktop:dist
          mv desktop/build/libs/Mindustry.jar desktop/build/libs/desktop.jar

        # TODO: Upload tests to builds repo pages
          
      - name: Push To Unstable
        if: ${{ github.repository == 'mindustry-antigrief/mindustry-client-v6' }}
        run: |
          git clone --depth=1 --branch=main https://github.com/mindustry-antigrief/mindustry-client-v6-builds ../mindustry-client-v6-builds
          cd ../mindustry-client-v6-builds
          git tag ${{ github.run_number }}
          git config --global user.name "Build Uploader"
          git push https://github.com/mindustry-antigreif-releases:${{ secrets.RELEASE_TOKEN }}@mindustry-antigrief/mindustry-client-v6-builds ${{ github.run_number }}
