name: Java Tests # Tests and pushes to unstable

on: [push, workflow_dispatch]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Run Tests
        run: |
          ./gradlew test desktop:dist
          mv desktop/build/libs/Mindustry.jar desktop/build/libs/desktop.jar

        # TODO: Upload tests to builds repo pages
          
      - name: Create Release
        if: ${{ github.repository == 'mindustry-antigrief/mindustry-client-v6' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Unstable ${{ github.run_number }}
          repo: mindustry-client-v6-builds
          draft: false
          prerelease: false
